# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('LoginName', models.CharField(max_length=50)),
                ('LoginPwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('Startprice', models.FloatField(max_length=8)),
                ('SalePrice', models.FloatField(max_length=8)),
                ('ProductIntro', models.CharField(max_length=50)),
                ('MaxCount', models.IntegerField(max_length=4)),
                ('Time', models.DateTimeField(max_length=8)),
                ('SellCount', models.IntegerField(max_length=4)),
                ('ProductImage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserPwd', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('TelNum', models.CharField(max_length=50)),
                ('Age', models.IntegerField(max_length=4)),
                ('Sex', models.CharField(max_length=50)),
                ('Addr', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuying.ProductInfo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuying.User'),
        ),
    ]
