# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='Startprice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Zipcode',
        ),
        migrations.AddField(
            model_name='orders',
            name='IsArrave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='IsFinish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='IsPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='IsPay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='IsStockStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='GroupID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='MaxCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='SellCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
