# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0002_auto_20160614_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='IsOut',
            field=models.BooleanField(default=True),
        ),
    ]
