# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0004_auto_20160702_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '\u516c\u544a', 'verbose_name_plural': '\u516c\u544a'},
        ),
    ]
