# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuying', '0006_auto_20160702_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ProductIntro',
            field=models.TextField(),
        ),
    ]
